eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
server:
  port: 8089
spring:
  application:
    name: Flight-Search
  data:
    mongodb:
      database: Flight
      host: localhost
      port: 27017
springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: FlightSearch
  paths-to-match: /**
  swagger-ui:
    path: /swagger-ui.html