server:
  port: 8761
spring:
  application:
    name: discovery-ws
  boot:
    admin:
      client:
        url:
        - http://localhost:8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true